from LinkedList import LinkedList

l = LinkedList(10)
print(str(l))
l.append(5)
print(str(l))
l.append(3)
print(str(l))
l.append(1)
print(str(l))
l.delete(idx=3)
print(str(l))
l.delete(idx=1)
print(str(l))
l.delete(idx=0)
print(str(l))
l.insert(idx=0, value=42)
print(str(l))
l.update(idx=0, value=21)
print(str(l))
l.update(idx=1, value=77)
print(str(l))
l.insert(idx=1, value=42)
print(str(l))
